# -*- coding: utf-8 -*-
"""มาตรฐานและข้อกำหนดแบบละเอียด (Granular Standards Model)

โครงสร้าง 2 ชั้น เพื่อให้เลือกมาตรฐานแบบรายฉบับได้ และไม่ต้องเขียนข้อกำหนดซ้ำ
-----------------------------------------------------------------------------
CONTROLS   = "สิ่งที่ระบบต้องทำ" 1 รายการ = 1 มาตรการ  เช่น "เก็บ log อย่างน้อย 90 วัน"
             แต่ละ control ผูกกับ capabilities ที่เครื่องมือต้องมี

FRAMEWORKS = "มาตรฐาน/กฎหมายรายฉบับ"  แต่ละฉบับอ้างถึง control พร้อมเลขข้อของตัวเอง
             control หนึ่งตัวถูกอ้างได้จากหลายฉบับ (เช่น log 90 วัน ถูกอ้างทั้งจาก
             พ.ร.บ.คอมพิวเตอร์ ม.26 และมาตรฐานขั้นต่ำ พ.ศ. 2566)

ผลที่ได้: เลือกมาตรฐานกี่ฉบับก็ได้ -> รวม control -> ได้ capability ที่ต้องมี
          -> ได้รายการเครื่องมือที่ต้องติดตั้ง -> คำนวณทรัพยากร

หมายเหตุความถูกต้องของการอ้างอิง
-----------------------------------------------------------------------------
ฉบับที่ตั้ง verify=True คือฉบับที่ผู้ใช้ควร "ตรวจเลขที่ประกาศและปีให้ตรงกับราชกิจจานุเบกษา
หรือเว็บไซต์ของหน่วยงานเจ้าของมาตรฐานก่อนนำไปอ้างใน TOR" เพราะชุดประกาศกลุ่มนี้มีการ
ออกเพิ่ม/ปรับปรุงเป็นระยะ โปรแกรมจะแสดงเครื่องหมายเตือนไว้ให้เห็นชัด
ตัวมาตรการ (control) ที่ผูกไว้ยังใช้ได้ตามปกติ เพราะเป็นสาระของข้อกำหนด ไม่ใช่เลขที่ประกาศ
"""

# ---------------------------------------------------------------------------
# กลุ่มของมาตรการ (ใช้จัดกลุ่มในหน้าจอ)
# ---------------------------------------------------------------------------
CONTROL_GROUPS = {
    "sdlc":     "กระบวนการพัฒนาและ Pipeline",
    "appsec":   "ความปลอดภัยของแอปพลิเคชัน",
    "supply":   "ความปลอดภัยของ Supply Chain",
    "crypto":   "การเข้ารหัสและการจัดการกุญแจ",
    "iam":      "การยืนยันตัวตนและสิทธิ์การเข้าถึง",
    "logging":  "การบันทึกและเฝ้าระวังเหตุการณ์",
    "ops":      "การปฏิบัติการและโครงสร้างพื้นฐาน",
    "privacy":  "การคุ้มครองข้อมูลส่วนบุคคล",
    "web":      "เว็บไซต์และการเข้าถึงที่เท่าเทียม",
    "ai":       "การกำกับดูแลโมเดล AI",
}

# severity: mandatory = ต้องมีทุกกรณี, conditional = ต้องมีเมื่อผลกระทบสูงขึ้น,
#           recommended = ควรมี
CONTROLS = [
    # ---------------- กระบวนการพัฒนาและ Pipeline ----------------
    dict(id="C-SDLC-REVIEW", group="sdlc", severity="mandatory", impact=["low", "medium", "high"],
         title_th="โค้ดต้องผ่าน Code Review และ Status Check ก่อน Merge เข้า main",
         detail_th="ภาครัฐบังคับอย่างน้อย 2 ผู้อนุมัติ และห้าม merge โค้ดที่ตกเกณฑ์",
         caps=["git_scm", "branch_protection", "quality_gate"]),
    dict(id="C-SDLC-TRACE", group="sdlc", severity="mandatory", impact=["low", "medium", "high"],
         title_th="Pipeline ทำงานอัตโนมัติและตรวจสอบย้อนหลังได้ 100% (Traceability)",
         detail_th="ต้องรู้ได้ว่า artifact ที่ขึ้น production มาจาก commit ใด ผ่านขั้นตอนอะไร ใครอนุมัติ",
         caps=["pipeline", "webhook", "audit_trail", "version_tag"]),
    dict(id="C-SDLC-SAST", group="sdlc", severity="mandatory", impact=["low", "medium", "high"],
         title_th="สแกนหาช่องโหว่ในซอร์สโค้ดแบบ Static (SAST) ทุกรอบ",
         detail_th="ตั้งเป็น Blocking Gate สำหรับช่องโหว่ระดับ Critical/High",
         caps=["sast"]),
    dict(id="C-SDLC-SECRET", group="sdlc", severity="mandatory", impact=["low", "medium", "high"],
         title_th="ห้าม Credential / Secret หลุดไปกับซอร์สโค้ดหรือ Log",
         detail_th="ต้องมี Secret Scanning ใน Pipeline และเก็บ Secret ใน Secret Manager",
         caps=["secret_scan", "secret_mgmt"]),
    dict(id="C-SDLC-QUALITY", group="sdlc", severity="mandatory", impact=["low", "medium", "high"],
         title_th="วัดคุณภาพโค้ดและ Test Coverage ตามเกณฑ์ที่กำหนด",
         detail_th="ภาครัฐมักกำหนด Coverage มากกว่า 80% และ Technical Debt ในระดับที่ยอมรับได้",
         caps=["code_quality", "unit_test"]),
    dict(id="C-SDLC-TEST", group="sdlc", severity="mandatory", impact=["low", "medium", "high"],
         title_th="ต้องมี Unit Test และ Integration Test ก่อนขึ้นระบบ",
         caps=["unit_test", "integration_test"]),
    dict(id="C-SDLC-THREAT", group="sdlc", severity="recommended", impact=["medium", "high"],
         title_th="ทำ Threat Modeling และ Security Architecture Review ตั้งแต่ออกแบบ",
         detail_th="ใช้ STRIDE / PASTA และทบทวนเมื่อสถาปัตยกรรมเปลี่ยน",
         caps=["code_quality", "quality_gate"]),

    # ---------------- ความปลอดภัยของแอปพลิเคชัน ----------------
    dict(id="C-APP-ACCESS", group="appsec", severity="mandatory", impact=["low", "medium", "high"],
         title_th="ควบคุมสิทธิ์การเข้าถึงฝั่ง Server ทุก Request (รวมป้องกัน SSRF)",
         detail_th="deny-by-default, ตรวจ authorization ทุกครั้ง, ใช้ allowlist ปลายทางกัน SSRF",
         caps=["sast", "api_security", "dast"]),
    dict(id="C-APP-INJECT", group="appsec", severity="mandatory", impact=["low", "medium", "high"],
         title_th="ป้องกัน Injection ทุกรูปแบบ (SQL, Command, XSS)",
         detail_th="parameterized query, allowlist validation, output encoding, CSP header",
         caps=["sast", "dast"]),
    dict(id="C-APP-AUTHN", group="appsec", severity="mandatory", impact=["low", "medium", "high"],
         title_th="Authentication ปลอดภัย: hashing ที่แข็งแรง, session rotation, rate limiting",
         caps=["iam_mfa", "api_security"]),
    dict(id="C-APP-ERROR", group="appsec", severity="recommended", impact=["low", "medium", "high"],
         title_th="จัดการข้อผิดพลาดแบบ fail-safe ไม่เปิดเผย stack trace",
         caps=["sast", "code_quality"]),
    dict(id="C-APP-DAST", group="appsec", severity="mandatory", impact=["medium", "high"],
         title_th="ทดสอบความปลอดภัยกับระบบที่รันอยู่จริง (DAST)",
         detail_th="ต้องรันบน Staging/UAT ที่มีข้อมูลเสมือนจริง ไม่ยิงจากเครื่องเดียวกับ target",
         caps=["dast"]),
    dict(id="C-APP-API", group="appsec", severity="mandatory", impact=["medium", "high"],
         title_th="ทดสอบความปลอดภัยของ API (Authn, RBAC, Input Validation, Fuzzing)",
         caps=["api_security"]),
    dict(id="C-APP-PENTEST", group="appsec", severity="conditional", impact=["medium", "high"],
         title_th="ประเมินช่องโหว่และทดสอบเจาะระบบ (VAPT) ก่อน Go-Live และเป็นระยะ",
         caps=["vapt", "dast"]),
    dict(id="C-APP-WAF", group="appsec", severity="mandatory", impact=["low", "medium", "high"],
         title_th="ติดตั้ง Web Application Firewall หน้าระบบที่เปิดสู่ภายนอก",
         caps=["waf"]),

    # ---------------- Supply Chain ----------------
    dict(id="C-SC-SBOM", group="supply", severity="mandatory", impact=["low", "medium", "high"],
         title_th="สร้าง SBOM ทุก artifact และเก็บคู่กับ artifact",
         detail_th="รูปแบบ SPDX หรือ CycloneDX เก็บนานเท่าอายุการใช้งานของระบบ",
         caps=["sbom"]),
    dict(id="C-SC-SCA", group="supply", severity="mandatory", impact=["low", "medium", "high"],
         title_th="ตรวจ Dependency เทียบฐานข้อมูลช่องโหว่ (CVE) ทุกรอบ",
         caps=["sca"]),
    dict(id="C-SC-LICENSE", group="supply", severity="conditional", impact=["medium", "high"],
         title_th="ตรวจลิขสิทธิ์ของ Open Source ให้สอดคล้องนโยบายองค์กร",
         detail_th="โครงการภาครัฐหลายแห่งห้ามใช้ GPL/AGPL ในงานเชิงพาณิชย์",
         caps=["license"]),
    dict(id="C-SC-SIGN", group="supply", severity="mandatory", impact=["medium", "high"],
         title_th="ลงนามดิจิทัลบน artifact และ Verify ลายเซ็นก่อน Deploy ทุกครั้ง",
         detail_th="การ Sign อย่างเดียวไม่พอ ต้องบังคับ Verify ที่ขั้น Deploy ด้วย",
         caps=["artifact_sign"]),
    dict(id="C-SC-REGISTRY", group="supply", severity="mandatory", impact=["low", "medium", "high"],
         title_th="ใช้ Private Container Registry ควบคุมที่มาของ Image และ Helm chart",
         detail_th="ห้าม pull จาก Docker Hub สาธารณะใน Production; เปิด immutable tag / ห้าม latest; "
                   "เก็บ Audit ว่าใคร push อะไร; สแกนช่องโหว่และ Verify ลายเซ็นก่อน Deploy "
                   "(Harbor / Zot / ACR / ECR / GAR / Nexus Docker hosted)",
         caps=["registry"]),
    dict(id="C-SC-PKG", group="supply", severity="mandatory", impact=["low", "medium", "high"],
         title_th="มีคลังแพ็กเกจภายใน (Maven / npm / PyPI / NuGet / apt) และ Proxy ของ upstream",
         detail_th="งานภาครัฐและ air-gap ต้องดึง dependency ผ่าน proxy ในองค์กร "
                   "เพื่อกัน typosquatting / dependency confusion และให้ตรวจ CVE/license ก่อนเข้าคลัง — "
                   "ห้ามให้ Pipeline ชี้ Maven Central หรือ registry.npmjs.org ตรงใน Production "
                   "(Nexus Repository, Azure Artifacts, Google Artifact Registry)",
         caps=["package_repo"]),
    dict(id="C-SC-PIN", group="supply", severity="mandatory", impact=["low", "medium", "high"],
         title_th="ตรึงเวอร์ชัน Dependency และทำให้ Build ซ้ำได้ (Reproducible)",
         caps=["version_tag", "build"]),
    dict(id="C-SC-PROMOTE", group="supply", severity="mandatory", impact=["low", "medium", "high"],
         title_th="โปรโมต Artifact เป็นขั้น (dev → uat → prod) และห้ามเขียนทับเวอร์ชันที่ปล่อยแล้ว",
         detail_th="แยก hosted repo แบบ snapshot/release หรือใช้ staging; ปิด redeploy ของเวอร์ชันที่ GA แล้ว; "
                   "เก็บ SBOM และลายเซ็นคู่กับ artifact ตามอายุการใช้งานของระบบ",
         caps=["version_tag", "package_repo"]),
    dict(id="C-SC-IMG", group="supply", severity="conditional", impact=["medium", "high"],
         title_th="สร้าง Container Image แบบควบคุมได้ (Rootless / Hermetic Build)",
         caps=["image_build", "build"]),
    dict(id="C-SC-CONTAINER", group="supply", severity="mandatory", impact=["low", "medium", "high"],
         title_th="สแกนช่องโหว่ของ Container Image ทุก Layer ก่อน Deploy",
         caps=["container_scan"]),

    # ---------------- การเข้ารหัส ----------------
    dict(id="C-CRY-TLS", group="crypto", severity="mandatory", impact=["low", "medium", "high"],
         title_th="ใช้ TLS 1.2 หรือ 1.3 เท่านั้น ห้าม Self-signed Certificate",
         caps=["tls_check"]),
    dict(id="C-CRY-KEY", group="crypto", severity="mandatory", impact=["low", "medium", "high"],
         title_th="จัดการกุญแจและ Secret อย่างปลอดภัย พร้อม Key Rotation",
         caps=["secret_mgmt"]),
    dict(id="C-CRY-PQC", group="crypto", severity="recommended", impact=["high"],
         title_th="ทำ Crypto Inventory (CBOM) และออกแบบให้เปลี่ยนอัลกอริทึมได้ (Crypto-Agility)",
         detail_th="เตรียมรองรับ Post-Quantum Cryptography ในอนาคต",
         caps=["crypto_agility", "tls_check"]),

    # ---------------- IAM ----------------
    dict(id="C-IAM-MFA", group="iam", severity="mandatory", impact=["low", "medium", "high"],
         title_th="บังคับ Multi-Factor Authentication สำหรับบัญชีสำคัญ",
         caps=["iam_mfa"]),
    dict(id="C-IAM-LEAST", group="iam", severity="mandatory", impact=["medium", "high"],
         title_th="ให้สิทธิ์เท่าที่จำเป็น (Least Privilege) และตรวจสิทธิ์ทุกการเรียกใช้",
         detail_th="แนวทาง Zero Trust: ไม่เชื่อถือเครือข่ายภายในโดยปริยาย",
         caps=["iam_mfa", "orchestration", "runtime_security"]),
    dict(id="C-IAM-REMOTE", group="iam", severity="conditional", impact=["medium", "high"],
         title_th="ควบคุมการเชื่อมต่อระยะไกลและสื่อบันทึกข้อมูลแบบถอดได้",
         caps=["iam_mfa", "config_mgmt"]),

    # ---------------- Logging & Detection ----------------
    dict(id="C-LOG-90", group="logging", severity="mandatory", impact=["low", "medium", "high"],
         title_th="เก็บ Log จราจรคอมพิวเตอร์ไม่น้อยกว่า 90 วัน และตรวจสอบย้อนหลังได้",
         detail_th="เป็นตัวกำหนดขนาด Data Disk ของระบบ Log โดยตรง",
         caps=["log_mgmt", "audit_trail"], param=dict(log_retention_days=90)),
    dict(id="C-LOG-CENTRAL", group="logging", severity="mandatory", impact=["low", "medium", "high"],
         title_th="รวบรวม Log ไว้ที่ศูนย์กลางที่แก้ไขย้อนหลังไม่ได้",
         caps=["log_mgmt"]),
    dict(id="C-LOG-SIEM", group="logging", severity="mandatory", impact=["medium", "high"],
         title_th="มีระบบเฝ้าระวังและแจ้งเตือนเหตุการณ์ด้านความปลอดภัย (SIEM / Alerting)",
         caps=["siem_alert", "monitoring"]),
    dict(id="C-LOG-AUDIT", group="logging", severity="mandatory", impact=["low", "medium", "high"],
         title_th="บันทึก Audit Trail ว่าใครทำอะไรเมื่อไหร่ และเก็บตามอายุที่กฎหมายกำหนด",
         detail_th="ภาครัฐมักต้องเก็บหลักฐานการอนุมัติและการเปลี่ยนแปลงระบบ 5-7 ปี",
         caps=["audit_trail"]),
    dict(id="C-LOG-NOTIFY", group="logging", severity="mandatory", impact=["low", "medium", "high"],
         title_th="แจ้งเหตุและยกระดับเหตุการณ์ได้ทันกรอบเวลาที่กฎหมายกำหนด",
         detail_th="PDPA กำหนด 72 ชั่วโมงต่อ PDPC และกฎหมายไซเบอร์กำหนดให้แจ้ง สกมช. โดยเร็ว",
         caps=["notify", "siem_alert"]),

    # ---------------- Operations ----------------
    dict(id="C-OPS-HARDEN", group="ops", severity="mandatory", impact=["low", "medium", "high"],
         title_th="มี Hardening Baseline และตรวจการตั้งค่าที่ผิดพลาดอย่างสม่ำเสมอ",
         caps=["config_mgmt"]),
    dict(id="C-OPS-IAC", group="ops", severity="mandatory", impact=["low", "medium", "high"],
         title_th="ตรวจไฟล์ Infrastructure as Code และบังคับ Policy-as-Code ก่อนใช้งาน",
         caps=["iac_scan"]),
    dict(id="C-OPS-CSPM", group="ops", severity="conditional", impact=["medium", "high"],
         title_th="ตรวจสถานะความปลอดภัยของโครงสร้างพื้นฐาน / คลาวด์เป็นระยะ",
         caps=["cspm"]),
    dict(id="C-OPS-RUNTIME", group="ops", severity="conditional", impact=["high"],
         title_th="เฝ้าระวังพฤติกรรมผิดปกติของ Container ตอนรันจริง (Runtime Security)",
         caps=["runtime_security"]),
    dict(id="C-OPS-MONITOR", group="ops", severity="mandatory", impact=["low", "medium", "high"],
         title_th="มีระบบ Observability เก็บ Metrics / Logs / Traces และตั้ง Alert",
         caps=["monitoring"]),
    dict(id="C-OPS-PERF", group="ops", severity="conditional", impact=["medium", "high"],
         title_th="ทดสอบประสิทธิภาพเทียบ SLA ก่อน Go-Live",
         caps=["perf_test"]),
    dict(id="C-OPS-DEPLOY", group="ops", severity="mandatory", impact=["low", "medium", "high"],
         title_th="มีกลยุทธ์การ Deploy ที่ย้อนกลับได้ (Rolling / Blue-Green / Canary)",
         caps=["deploy_strategy", "orchestration"]),
    dict(id="C-OPS-BACKUP", group="ops", severity="mandatory", impact=["low", "medium", "high"],
         title_th="สำรองข้อมูลและ ทดสอบการกู้คืนจริง ไม่ใช่แค่สำรองผ่าน",
         caps=["backup_dr"]),
    dict(id="C-OPS-BCP", group="ops", severity="conditional", impact=["medium", "high"],
         title_th="มีแผนความต่อเนื่องทางธุรกิจและการกู้คืนระบบ พร้อมซ้อมแผนเป็นประจำ",
         caps=["backup_dr", "audit_trail"]),

    # ---------------- Privacy ----------------
    dict(id="C-PRV-MEASURE", group="privacy", severity="mandatory", impact=["low", "medium", "high"],
         title_th="มีมาตรการรักษาความมั่นคงปลอดภัยที่เหมาะสมกับข้อมูลส่วนบุคคล",
         detail_th="ครอบคลุมการเข้ารหัส การควบคุมสิทธิ์ และการบันทึกเหตุการณ์",
         caps=["secret_mgmt", "iam_mfa", "log_mgmt", "tls_check"]),
    dict(id="C-PRV-BREACH", group="privacy", severity="mandatory", impact=["low", "medium", "high"],
         title_th="ตรวจจับเหตุละเมิดข้อมูลส่วนบุคคลได้เร็วพอที่จะแจ้งภายในกรอบเวลา",
         caps=["siem_alert", "log_mgmt", "notify"]),
    dict(id="C-PRV-MINIMIZE", group="privacy", severity="mandatory", impact=["low", "medium", "high"],
         title_th="ไม่ให้ข้อมูลส่วนบุคคลรั่วไหลไปกับ Log, Artifact หรือชุดข้อมูลทดสอบ",
         caps=["secret_scan", "log_mgmt"]),

    # ---------------- Web / Accessibility ----------------
    dict(id="C-WEB-A11Y", group="web", severity="mandatory", impact=["low", "medium", "high"],
         title_th="เว็บไซต์ต้องผ่าน WCAG 2.1 หรือ 2.2 ระดับ AA",
         detail_th="เป็นข้อที่โครงการเว็บภาครัฐตกบ่อยที่สุด เพราะไม่มีการทดสอบใน Pipeline",
         caps=["accessibility"]),
    dict(id="C-WEB-SELF", group="web", severity="mandatory", impact=["low", "medium", "high"],
         title_th="ประเมินตนเองอย่างน้อยปีละ 1 ครั้ง และรายงานผลต่อผู้บริหาร",
         caps=["audit_trail", "vapt"]),

    # ---------------- AI ----------------
    dict(id="C-AI-GOV", group="ai", severity="conditional", impact=["medium", "high"],
         title_th="กำกับดูแลเวอร์ชันโมเดล ที่มาของข้อมูล และเกณฑ์ผ่านก่อนนำโมเดลขึ้นใช้",
         caps=["version_tag", "registry", "quality_gate", "artifact_sign"]),
    dict(id="C-AI-DRIFT", group="ai", severity="conditional", impact=["medium", "high"],
         title_th="เฝ้าระวัง Model Drift และ Bias หลังนำขึ้นใช้งาน",
         caps=["monitoring", "runtime_security"]),
]

# ---------------------------------------------------------------------------
# มาตรฐาน / กฎหมายรายฉบับ
#   controls = {control_id: "เลขข้ออ้างอิงของฉบับนั้น"}
#              หรือ {control_id: dict(clause="...", severity="recommended")} เพื่อลดระดับบังคับ
#   verify=True = ควรตรวจเลขที่ประกาศ/ปีกับแหล่งทางการก่อนอ้างใน TOR
# ---------------------------------------------------------------------------
FRAMEWORK_FAMILIES = {
    "th-law":    dict(label_th="กฎหมายไทย (พระราชบัญญัติ / พระราชกฤษฎีกา)", region="th", order=1),
    "th-ncsa":   dict(label_th="ประกาศ สกมช. (NCSA)", region="th", order=2),
    "th-pdpc":   dict(label_th="ประกาศคณะกรรมการคุ้มครองข้อมูลส่วนบุคคล (PDPC)", region="th", order=3),
    "th-dga":    dict(label_th="มาตรฐานรัฐบาลดิจิทัล (มสพร. / DGA)", region="th", order=4),
    "th-etda":   dict(label_th="ข้อเสนอแนะมาตรฐาน (ขมธอ.) — ETDA", region="th", order=5),
    "th-other":  dict(label_th="เกณฑ์อื่นในประเทศ", region="th", order=6),
    "iso":       dict(label_th="ISO / IEC", region="intl", order=7),
    "owasp":     dict(label_th="OWASP", region="intl", order=8),
    "nist":      dict(label_th="NIST", region="intl", order=9),
    "cis":       dict(label_th="CIS", region="intl", order=10),
    "supplychain": dict(label_th="Supply Chain & SBOM", region="intl", order=11),
    "industry":  dict(label_th="มาตรฐานอุตสาหกรรม / การตรวจรับรอง", region="intl", order=12),
    "w3c":       dict(label_th="W3C", region="intl", order=13),
}

FRAMEWORKS = [
    # ======================= กฎหมายไทย =======================
    dict(id="TH-CCA-2560", family="th-law", verify=False,
         name_th="พ.ร.บ. ว่าด้วยการกระทำความผิดเกี่ยวกับคอมพิวเตอร์ พ.ศ. 2550 "
                 "และที่แก้ไขเพิ่มเติม (ฉบับที่ 2) พ.ศ. 2560",
         short_th="พ.ร.บ. คอมพิวเตอร์ 2550/2560", authority="กระทรวงดิจิทัลเพื่อเศรษฐกิจและสังคม",
         scope_th="ผู้ให้บริการต้องเก็บข้อมูลจราจรทางคอมพิวเตอร์ไม่น้อยกว่า 90 วัน",
         controls={"C-LOG-90": "ม.26", "C-LOG-CENTRAL": "ม.26", "C-LOG-AUDIT": "ม.26"}),

    dict(id="TH-CYBER-2562", family="th-law", verify=False,
         name_th="พ.ร.บ. การรักษาความมั่นคงปลอดภัยไซเบอร์ พ.ศ. 2562",
         short_th="พ.ร.บ. ไซเบอร์ 2562", authority="สกมช. (NCSA)",
         scope_th="หน่วยงานรัฐและโครงสร้างพื้นฐานสำคัญ (CII) 7 ภาคส่วน",
         controls={"C-APP-PENTEST": "ม.54-57", "C-LOG-SIEM": "ม.56", "C-LOG-NOTIFY": "ม.57",
                   "C-OPS-BCP": "ม.3, ม.62", "C-LOG-AUDIT": "ม.54",
                   "C-OPS-DEPLOY": "ม.62 การรักษาความต่อเนื่องของบริการ"}),

    dict(id="TH-PDPA-2562", family="th-law", verify=False,
         name_th="พ.ร.บ. คุ้มครองข้อมูลส่วนบุคคล พ.ศ. 2562 (PDPA)",
         short_th="PDPA 2562", authority="PDPC",
         scope_th="ทุกองค์กรที่เก็บ ใช้ หรือเปิดเผยข้อมูลส่วนบุคคล",
         controls={"C-PRV-MEASURE": "ม.37", "C-PRV-BREACH": "ม.37(4)", "C-PRV-MINIMIZE": "ม.37",
                   "C-CRY-KEY": "ม.37", "C-IAM-LEAST": "ม.37", "C-LOG-AUDIT": "ม.39 (RoPA)"}),

    dict(id="TH-EGOV-2565", family="th-law", verify=False,
         name_th="พ.ร.บ. การปฏิบัติราชการทางอิเล็กทรอนิกส์ พ.ศ. 2565",
         short_th="พ.ร.บ. ปฏิบัติราชการทางอิเล็กทรอนิกส์ 2565", authority="สำนักงาน ก.พ.ร. / DGA",
         scope_th="การให้บริการและติดต่อราชการผ่านช่องทางอิเล็กทรอนิกส์",
         controls={"C-LOG-AUDIT": "การเก็บหลักฐานทางอิเล็กทรอนิกส์",
                   "C-SDLC-TRACE": "ความน่าเชื่อถือของระบบ", "C-CRY-TLS": "ความปลอดภัยของช่องทาง"}),

    dict(id="TH-SECURE-TXN-2553", family="th-law", verify=True,
         name_th="พ.ร.ฎ. กำหนดวิธีการแบบปลอดภัยในการทำธุรกรรมทางอิเล็กทรอนิกส์ พ.ศ. 2553",
         short_th="พ.ร.ฎ. วิธีการแบบปลอดภัย 2553", authority="ETDA",
         scope_th="ธุรกรรมทางอิเล็กทรอนิกส์ที่ต้องใช้วิธีการแบบปลอดภัยระดับพื้นฐานถึงเคร่งครัด",
         controls={"C-CRY-TLS": "การรักษาความลับของข้อมูล", "C-IAM-MFA": "การยืนยันตัวตน",
                   "C-LOG-CENTRAL": "การบันทึกเหตุการณ์", "C-OPS-BACKUP": "ความพร้อมใช้ของระบบ"}),

    # ======================= ประกาศ สกมช. =======================
    dict(id="TH-NCSA-MIN-2566", family="th-ncsa", verify=False,
         name_th="มาตรฐานขั้นต่ำของข้อมูลหรือระบบสารสนเทศ พ.ศ. 2566",
         short_th="มาตรฐานขั้นต่ำ 2566", authority="สกมช. (NCSA)",
         scope_th="จัดระดับผลกระทบ ต่ำ / กลาง / สูง แล้วบังคับมาตรการตามระดับ",
         controls={"C-LOG-90": "Log Management", "C-LOG-AUDIT": "Log Management",
                   "C-IAM-REMOTE": "ระดับกลาง — Remote Connection",
                   "C-APP-PENTEST": "ระดับสูง — VAPT",
                   "C-SC-SBOM": "ระดับสูง — Third Party Management",
                   "C-SC-SCA": "ระดับสูง — Third Party Management",
                   "C-SC-REGISTRY": "ระดับสูง — Third Party Management / แหล่งซอฟต์แวร์ที่อนุมัติ",
                   "C-SC-PKG": "ระดับสูง — Third Party Management / คลังแพ็กเกจภายใน",
                   "C-OPS-BCP": "ระดับสูง — Resilience & Recovery",
                   "C-OPS-BACKUP": "ระดับสูง — Resilience & Recovery",
                   "C-OPS-HARDEN": "การควบคุมเชิงเทคนิค"}),

    dict(id="TH-NCSA-CLOUD-2567", family="th-ncsa", verify=False,
         name_th="มาตรฐานความมั่นคงปลอดภัยระบบคลาวด์ พ.ศ. 2567",
         short_th="มาตรฐานคลาวด์ 2567", authority="สกมช. (NCSA)",
         scope_th="การใช้บริการคลาวด์ของหน่วยงานรัฐภายใต้นโยบาย Cloud First",
         controls={"C-OPS-IAC": "Cloud Infrastructure Security", "C-OPS-CSPM": "Cloud Infrastructure Security",
                   "C-IAM-LEAST": "Access Control", "C-CRY-KEY": "Data Encryption",
                   "C-LOG-CENTRAL": "Operation Security", "C-OPS-MONITOR": "Continuous Monitoring",
                   "C-SC-REGISTRY": "แหล่งอิมเมจและแพ็กเกจจากคลังที่อนุมัติ",
                   "C-SC-PKG": "คลังแพ็กเกจ / proxy ในองค์กรเมื่อใช้คลาวด์แบบ hybrid"}),

    dict(id="TH-NCSA-WEB-2568", family="th-ncsa", verify=False,
         name_th="มาตรฐานการรักษาความมั่นคงปลอดภัยเว็บไซต์ พ.ศ. 2568",
         short_th="มาตรฐานเว็บไซต์ 2568", authority="สกมช. (NCSA)",
         scope_th="เว็บไซต์และเว็บแอปพลิเคชันของหน่วยงานรัฐ ทั้ง On-premise และคลาวด์",
         controls={"C-IAM-MFA": "Website Security Operation", "C-CRY-TLS": "Website Security Operation",
                   "C-APP-WAF": "Website Security Operation", "C-LOG-CENTRAL": "Logging & Monitoring",
                   "C-LOG-SIEM": "Logging & Monitoring", "C-APP-PENTEST": "Penetration Testing",
                   "C-SDLC-SAST": "Secure Coding", "C-WEB-SELF": "Self-Assessment รายปี",
                   "C-OPS-BACKUP": "Website Security Governance"}),

    dict(id="TH-NCSA-RAM-2564", family="th-ncsa", verify=True,
         name_th="ประมวลแนวทางปฏิบัติและกรอบมาตรฐานด้านการรักษาความมั่นคงปลอดภัยไซเบอร์ พ.ศ. 2564",
         short_th="กรอบมาตรฐานไซเบอร์ 2564", authority="สกมช. (NCSA)",
         scope_th="กรอบการประเมินความเสี่ยงและการปฏิบัติสำหรับหน่วยงานภายใต้กฎหมายไซเบอร์",
         controls={"C-LOG-SIEM": "การเฝ้าระวัง", "C-OPS-BCP": "การรับมือและกู้คืน",
                   "C-APP-PENTEST": "การประเมินความเสี่ยง", "C-OPS-HARDEN": "การควบคุมเชิงเทคนิค"}),

    # ======================= ประกาศ PDPC =======================
    dict(id="TH-PDPC-SEC-2565", family="th-pdpc", verify=True,
         name_th="ประกาศคณะกรรมการคุ้มครองข้อมูลส่วนบุคคล เรื่อง มาตรการรักษาความมั่นคงปลอดภัย"
                 "ของผู้ควบคุมข้อมูลส่วนบุคคล พ.ศ. 2565",
         short_th="ประกาศ PDPC มาตรการความปลอดภัย 2565", authority="PDPC",
         scope_th="มาตรการเชิงบริหาร เชิงเทคนิค และเชิงกายภาพ ที่ผู้ควบคุมข้อมูลต้องจัดให้มี",
         controls={"C-PRV-MEASURE": "มาตรการเชิงเทคนิค", "C-IAM-MFA": "การควบคุมการเข้าถึง",
                   "C-LOG-CENTRAL": "การบันทึกการเข้าถึง", "C-CRY-TLS": "การเข้ารหัสข้อมูล",
                   "C-CRY-KEY": "การบริหารกุญแจ"}),

    dict(id="TH-PDPC-BREACH-2565", family="th-pdpc", verify=True,
         name_th="ประกาศคณะกรรมการคุ้มครองข้อมูลส่วนบุคคล เรื่อง หลักเกณฑ์และวิธีการ"
                 "ในการแจ้งเหตุการละเมิดข้อมูลส่วนบุคคล พ.ศ. 2565",
         short_th="ประกาศ PDPC แจ้งเหตุละเมิด 2565", authority="PDPC",
         scope_th="การประเมินความเสี่ยงและการแจ้งเหตุละเมิดภายใน 72 ชั่วโมง",
         controls={"C-PRV-BREACH": "การแจ้งภายใน 72 ชั่วโมง", "C-LOG-NOTIFY": "ช่องทางการแจ้งเหตุ",
                   "C-LOG-SIEM": "การตรวจพบเหตุ"}),

    # ======================= มาตรฐานรัฐบาลดิจิทัล =======================
    dict(id="TH-DGA-MSPR11-2566", family="th-dga", verify=False,
         name_th="มสพร. 11-2566 มาตรฐานเว็บไซต์ภาครัฐ เวอร์ชัน 3.0",
         short_th="มสพร. 11-2566 เว็บไซต์ภาครัฐ 3.0", authority="DGA (สพร.)",
         scope_th="เว็บไซต์ .go.th — โครงสร้าง 8 ส่วน, WCAG 2.1/2.2 AA, TLS 1.2/1.3, Open Data",
         controls={"C-WEB-A11Y": "Web Accessibility (WCAG AA)", "C-CRY-TLS": "ความมั่นคงปลอดภัยทางเทคนิค",
                   "C-APP-WAF": dict(clause="มาตรการทางเทคนิค (แนะนำ)", severity="recommended"),
                   "C-OPS-BACKUP": "แผนสำรองข้อมูล", "C-PRV-MEASURE": "การคุ้มครองข้อมูลส่วนบุคคล"}),

    dict(id="TH-DGA-OPENDATA", family="th-dga", verify=True,
         name_th="มาตรฐานข้อมูลเปิดภาครัฐ (Open Data) และธรรมาภิบาลข้อมูล",
         short_th="มาตรฐานข้อมูลเปิดภาครัฐ", authority="DGA (สพร.)",
         scope_th="เผยแพร่ข้อมูลในรูปแบบที่เครื่องอ่านได้ (CSV/JSON/XML) และมีธรรมาภิบาลข้อมูล",
         controls={"C-LOG-AUDIT": "ธรรมาภิบาลข้อมูล", "C-SDLC-TRACE": "ที่มาของข้อมูล (Provenance)"}),

    # ======================= ETDA =======================
    dict(id="TH-ETDA-ISEC", family="th-etda", verify=True,
         name_th="ข้อเสนอแนะมาตรฐาน (ขมธอ.) ด้านการรักษาความมั่นคงปลอดภัยสารสนเทศ — ETDA",
         short_th="ขมธอ. ความมั่นคงปลอดภัยสารสนเทศ", authority="ETDA",
         scope_th="แนวทางการจัดการความมั่นคงปลอดภัยสารสนเทศสำหรับธุรกรรมทางอิเล็กทรอนิกส์",
         controls={"C-OPS-HARDEN": "การตั้งค่าอย่างปลอดภัย", "C-LOG-CENTRAL": "การบันทึกเหตุการณ์",
                   "C-IAM-LEAST": "การควบคุมการเข้าถึง", "C-CRY-TLS": "การเข้ารหัสข้อมูล",
                   "C-SDLC-SAST": "การพัฒนาซอฟต์แวร์อย่างปลอดภัย"}),

    dict(id="TH-ETDA-CLOUD", family="th-etda", verify=True,
         name_th="ข้อเสนอแนะมาตรฐาน (ขมธอ.) การใช้บริการคลาวด์ — ETDA",
         short_th="ขมธอ. การใช้บริการคลาวด์", authority="ETDA",
         scope_th="แนวทางการเลือกและควบคุมผู้ให้บริการคลาวด์ และความรับผิดชอบร่วมกัน",
         controls={"C-OPS-CSPM": "การควบคุมผู้ให้บริการ", "C-CRY-KEY": "การจัดการกุญแจของผู้ใช้บริการ",
                   "C-OPS-BACKUP": "การสำรองและย้ายข้อมูล", "C-IAM-LEAST": "การควบคุมการเข้าถึง"}),

    dict(id="TH-ETDA-ESIGN", family="th-etda", verify=True,
         name_th="ข้อเสนอแนะมาตรฐาน (ขมธอ.) ลายมือชื่ออิเล็กทรอนิกส์และเอกสารอิเล็กทรอนิกส์ — ETDA",
         short_th="ขมธอ. ลายมือชื่อ/เอกสารอิเล็กทรอนิกส์", authority="ETDA",
         scope_th="ความน่าเชื่อถือของลายมือชื่ออิเล็กทรอนิกส์และการรักษาความครบถ้วนของเอกสาร",
         controls={"C-SC-SIGN": "ความครบถ้วนและการลงลายมือชื่อ", "C-CRY-KEY": "การจัดการกุญแจ",
                   "C-LOG-AUDIT": "การเก็บหลักฐาน"}),

    # ======================= เกณฑ์อื่นในประเทศ =======================
    dict(id="TH-ITA-NACC", family="th-other", verify=True,
         name_th="การประเมินคุณธรรมและความโปร่งใสในการดำเนินงานของหน่วยงานภาครัฐ (ITA)",
         short_th="ITA (ป.ป.ช.)", authority="สำนักงาน ป.ป.ช.",
         scope_th="การเปิดเผยข้อมูลบนเว็บไซต์และความโปร่งใสของกระบวนการ",
         controls={"C-LOG-AUDIT": "การเปิดเผยข้อมูลและตรวจสอบได้",
                   "C-WEB-SELF": "การประเมินตนเองรายปี"}),

    # ======================= ISO / IEC =======================
    dict(id="ISO-27001-2022", family="iso", verify=False,
         name_th="ISO/IEC 27001:2022 — ระบบบริหารความมั่นคงปลอดภัยสารสนเทศ (ISMS)",
         short_th="ISO/IEC 27001:2022", authority="ISO/IEC",
         scope_th="ชุดควบคุม Annex A 93 ข้อ ใช้อ้างอิงร่วมกับมาตรฐานไทยเกือบทุกฉบับ",
         controls={"C-SDLC-REVIEW": "A.8.25, A.8.28", "C-SDLC-TEST": "A.8.29",
                   "C-SDLC-THREAT": "A.8.27", "C-OPS-HARDEN": "A.8.9",
                   "C-LOG-CENTRAL": "A.8.15", "C-LOG-AUDIT": "A.8.15",
                   "C-IAM-LEAST": "A.5.15, A.8.2", "C-CRY-KEY": "A.8.24",
                   "C-SC-LICENSE": "A.5.32", "C-SC-REGISTRY": "A.8.9, A.5.23",
                   "C-SC-PKG": "A.8.8 Technical vulnerability, A.5.19 Supplier relationships",
                   "C-SC-PROMOTE": "A.8.32 Change management",
                   "C-OPS-BACKUP": "A.8.13",
                   "C-APP-PENTEST": "A.8.8", "C-OPS-PERF": "A.8.6"}),

    dict(id="ISO-27002-2022", family="iso", verify=False,
         name_th="ISO/IEC 27002:2022 — แนวปฏิบัติของมาตรการควบคุมความมั่นคงปลอดภัยสารสนเทศ",
         short_th="ISO/IEC 27002:2022", authority="ISO/IEC",
         scope_th="คำอธิบายวิธีปฏิบัติของแต่ละมาตรการใน 27001",
         controls={"C-OPS-HARDEN": "8.9", "C-SDLC-SAST": "8.28", "C-LOG-CENTRAL": "8.15",
                   "C-SC-SCA": "8.8", "C-SC-PKG": "8.8", "C-SC-REGISTRY": "8.9",
                   "C-SDLC-SECRET": "8.24"}),

    dict(id="ISO-27017-2015", family="iso", verify=False,
         name_th="ISO/IEC 27017:2015 — มาตรการควบคุมความปลอดภัยสำหรับบริการคลาวด์",
         short_th="ISO/IEC 27017", authority="ISO/IEC",
         scope_th="ส่วนขยายของ 27002 สำหรับผู้ให้บริการและผู้ใช้บริการคลาวด์",
         controls={"C-OPS-CSPM": "CLD.9", "C-IAM-LEAST": "CLD.9.5", "C-LOG-CENTRAL": "CLD.12.4",
                   "C-CRY-KEY": "CLD.10"}),

    dict(id="ISO-27018-2019", family="iso", verify=False,
         name_th="ISO/IEC 27018:2019 — การคุ้มครองข้อมูลส่วนบุคคล (PII) บนคลาวด์สาธารณะ",
         short_th="ISO/IEC 27018", authority="ISO/IEC",
         scope_th="ข้อกำหนดเพิ่มเติมเมื่อประมวลผล PII ในฐานะผู้ประมวลผลบนคลาวด์สาธารณะ",
         controls={"C-PRV-MEASURE": "A.11", "C-PRV-MINIMIZE": "A.10", "C-LOG-AUDIT": "A.12"}),

    dict(id="ISO-27701-2019", family="iso", verify=False,
         name_th="ISO/IEC 27701:2019 — ระบบบริหารจัดการข้อมูลส่วนบุคคล (PIMS)",
         short_th="ISO/IEC 27701", authority="ISO/IEC",
         scope_th="ส่วนขยายของ 27001/27002 สำหรับความเป็นส่วนตัว ใช้แสดงความสอดคล้องกับ PDPA/GDPR",
         controls={"C-PRV-MEASURE": "6.x", "C-PRV-BREACH": "A.7.3", "C-PRV-MINIMIZE": "A.7.4",
                   "C-LOG-AUDIT": "A.7.2"}),

    dict(id="ISO-29100-2011", family="iso", verify=False,
         name_th="ISO/IEC 29100:2011 — กรอบแนวคิดด้านความเป็นส่วนตัว (Privacy Framework)",
         short_th="ISO/IEC 29100", authority="ISO/IEC",
         scope_th="หลักการ 11 ข้อด้านความเป็นส่วนตัว ใช้เป็นฐานของ 27701 และ Privacy by Design",
         controls={"C-PRV-MINIMIZE": "Data minimization", "C-PRV-MEASURE": "Information security"}),

    dict(id="ISO-27034", family="iso", verify=True,
         name_th="ISO/IEC 27034 — ความมั่นคงปลอดภัยของแอปพลิเคชัน (Application Security)",
         short_th="ISO/IEC 27034", authority="ISO/IEC",
         scope_th="กรอบการฝัง security เข้าไปในวงจรชีวิตของแอปพลิเคชัน",
         controls={"C-SDLC-SAST": "ASC", "C-SDLC-THREAT": "Application Security Life Cycle",
                   "C-APP-DAST": "Verification", "C-SDLC-TEST": "Verification"}),

    dict(id="ISO-25010-2023", family="iso", verify=False,
         name_th="ISO/IEC 25010:2023 — แบบจำลองคุณภาพของระบบและซอฟต์แวร์",
         short_th="ISO/IEC 25010:2023", authority="ISO/IEC",
         scope_th="คุณลักษณะคุณภาพ 9 ด้าน ใช้กำหนดเกณฑ์ตรวจรับในโครงการ",
         controls={"C-SDLC-QUALITY": "Maintainability", "C-SDLC-TEST": "Functional Suitability",
                   "C-OPS-PERF": "Performance Efficiency"}),

    dict(id="ISO-42001-2023", family="iso", verify=False,
         name_th="ISO/IEC 42001:2023 — ระบบบริหารจัดการปัญญาประดิษฐ์ (AI Management System)",
         short_th="ISO/IEC 42001:2023", authority="ISO/IEC",
         scope_th="การกำกับดูแลระบบ AI ตลอดวงจรชีวิต รวมความโปร่งใสและการจัดการความเสี่ยง",
         controls={"C-AI-GOV": "A.6 AI system life cycle", "C-AI-DRIFT": "A.9 Performance monitoring",
                   "C-LOG-AUDIT": "A.5 Records"}),

    dict(id="ISO-22301-2019", family="iso", verify=False,
         name_th="ISO 22301:2019 — ระบบบริหารความต่อเนื่องทางธุรกิจ (BCMS)",
         short_th="ISO 22301:2019", authority="ISO",
         scope_th="แผนความต่อเนื่อง การกู้คืน และการซ้อมแผน",
         controls={"C-OPS-BCP": "8.4 Business continuity plans", "C-OPS-BACKUP": "8.4.4"}),

    # ======================= OWASP =======================
    dict(id="OWASP-TOP10-2025", family="owasp", verify=False,
         name_th="OWASP Top 10:2025 — ช่องโหว่เว็บแอปพลิเคชัน 10 อันดับ พร้อมประเด็น Post-Quantum",
         short_th="OWASP Top 10:2025", authority="OWASP Foundation",
         scope_th="A01-A10 ใช้เป็นเกณฑ์ขั้นต่ำของการทดสอบความปลอดภัยแอปพลิเคชัน",
         controls={"C-APP-ACCESS": "A01 Broken Access Control (รวม SSRF)",
                   "C-OPS-HARDEN": "A02 Security Misconfiguration",
                   "C-OPS-IAC": "A02 Security Misconfiguration",
                   "C-SC-SBOM": "A03 Software Supply Chain Failures",
                   "C-SC-SCA": "A03 Software Supply Chain Failures",
                   "C-SC-REGISTRY": "A03 Software Supply Chain Failures",
                   "C-SC-PKG": "A03 Private package repo / proxy (กัน typosquatting)",
                   "C-SC-PROMOTE": "A03/A08 Immutable release + promotion",
                   "C-SC-CONTAINER": "A02/A03 Container image vulnerabilities",
                   "C-CRY-TLS": "A04 Cryptographic Failures",
                   "C-CRY-KEY": "A04 Cryptographic Failures",
                   "C-APP-INJECT": "A05 Injection",
                   "C-SDLC-THREAT": "A06 Insecure Design",
                   "C-APP-AUTHN": "A07 Authentication Failures",
                   "C-SC-SIGN": "A08 Software/Data Integrity Failures",
                   "C-SC-PIN": "A08 Software/Data Integrity Failures",
                   "C-LOG-CENTRAL": "A09 Logging & Alerting Failures",
                   "C-LOG-SIEM": "A09 Logging & Alerting Failures",
                   "C-APP-ERROR": "A10 Mishandling of Exceptional Conditions",
                   "C-CRY-PQC": "Post-Quantum Threat & Crypto-Agility"}),

    dict(id="OWASP-ASVS-5", family="owasp", verify=True,
         name_th="OWASP Application Security Verification Standard (ASVS) 5.0",
         short_th="OWASP ASVS 5.0", authority="OWASP Foundation",
         scope_th="รายการข้อกำหนดที่ตรวจสอบได้ 3 ระดับ ใช้เขียนเกณฑ์ตรวจรับใน TOR ได้ตรงตัว",
         controls={"C-APP-AUTHN": "V2 Authentication", "C-APP-ACCESS": "V4 Access Control",
                   "C-APP-INJECT": "V5 Validation & Encoding", "C-CRY-KEY": "V6 Cryptography",
                   "C-APP-ERROR": "V7 Error Handling & Logging",
                   "C-LOG-CENTRAL": "V7 Error Handling & Logging",
                   "C-SC-PKG": "V14 Configuration / dependency management",
                   "C-SC-REGISTRY": "V14 Build environment / trusted artifacts"}),

    dict(id="OWASP-API-2023", family="owasp", verify=False,
         name_th="OWASP API Security Top 10:2023",
         short_th="OWASP API Top 10:2023", authority="OWASP Foundation",
         scope_th="ช่องโหว่เฉพาะของ API เช่น BOLA, BOPLA, Unrestricted Resource Consumption",
         controls={"C-APP-API": "API1-API10", "C-APP-ACCESS": "API1 BOLA / API3 BOPLA",
                   "C-APP-AUTHN": "API2 Broken Authentication"}),

    dict(id="OWASP-SAMM-2", family="owasp", verify=False,
         name_th="OWASP SAMM 2 — แบบประเมินวุฒิภาวะด้านความปลอดภัยของกระบวนการพัฒนา",
         short_th="OWASP SAMM 2", authority="OWASP Foundation",
         scope_th="ประเมินวุฒิภาวะ 5 หน้าที่ 15 practice ใช้วางแผนยกระดับทีมพัฒนา",
         controls={"C-SDLC-THREAT": "Design — Threat Assessment",
                   "C-SDLC-SAST": "Verification — Security Testing",
                   "C-APP-DAST": "Verification — Security Testing",
                   "C-SDLC-REVIEW": "Implementation — Secure Build"}),

    dict(id="OWASP-MASVS", family="owasp", verify=True,
         name_th="OWASP Mobile Application Security Verification Standard (MASVS)",
         short_th="OWASP MASVS", authority="OWASP Foundation",
         scope_th="ใช้เมื่อโครงการมีแอปพลิเคชันบนมือถือ",
         controls={"C-APP-AUTHN": "MASVS-AUTH", "C-CRY-KEY": "MASVS-CRYPTO",
                   "C-APP-ERROR": "MASVS-CODE"}),

    # ======================= NIST =======================
    dict(id="NIST-SSDF-800-218", family="nist", verify=False,
         name_th="NIST SP 800-218 — Secure Software Development Framework (SSDF)",
         short_th="NIST SSDF (SP 800-218)", authority="NIST",
         scope_th="กลุ่มปฏิบัติ PO / PS / PW / RV ใช้อ้างอิงเป็นเกณฑ์ Secure SDLC",
         controls={"C-SDLC-TRACE": "PO.3 Implement Supporting Toolchains",
                   "C-SDLC-REVIEW": "PW.7 Review Human-Readable Code",
                   "C-SDLC-SAST": "PW.8 Test Executable Code",
                   "C-SDLC-TEST": "PW.8 Test Executable Code",
                   "C-SC-SBOM": "PS.3 Archive and Protect Each Release",
                   "C-SC-SIGN": "PS.2 Provide a Mechanism for Verifying Integrity",
                   "C-SC-PIN": "PW.4 Reuse Existing Software Securely",
                   "C-SC-PKG": "PW.4 Reuse Existing Software Securely (trusted package repo)",
                   "C-SC-REGISTRY": "PS.3 Archive and Protect Each Release",
                   "C-SC-PROMOTE": "PS.3 Archive and Protect Each Release"}),

    dict(id="NIST-800-161r1", family="nist", verify=False,
         name_th="NIST SP 800-161r1 — การบริหารความเสี่ยงห่วงโซ่อุปทานไซเบอร์ (C-SCRM)",
         short_th="NIST SP 800-161r1", authority="NIST",
         scope_th="ความเสี่ยงจาก Third Party, Dependency Confusion, Typosquatting",
         controls={"C-SC-SBOM": "SR-4 Provenance", "C-SC-SCA": "SR-3",
                   "C-SC-REGISTRY": "SR-11 Component Authenticity",
                   "C-SC-PKG": "SR-3 / SR-5 Acquisition — private proxy of upstream",
                   "C-SC-PROMOTE": "SR-4 Provenance of promoted artifacts",
                   "C-SC-SIGN": "SR-4(3)",
                   "C-SC-LICENSE": "SR-5"}),

    dict(id="NIST-800-207", family="nist", verify=False,
         name_th="NIST SP 800-207 — Zero Trust Architecture",
         short_th="NIST SP 800-207", authority="NIST",
         scope_th="ไม่เชื่อถือเครือข่ายภายในโดยปริยาย ตรวจสอบทุกการเข้าถึง",
         controls={"C-IAM-LEAST": "Tenet 1-7", "C-IAM-MFA": "Policy Enforcement Point",
                   "C-OPS-RUNTIME": "Continuous Diagnostics", "C-LOG-SIEM": "Continuous Monitoring"}),

    dict(id="NIST-800-63B", family="nist", verify=False,
         name_th="NIST SP 800-63B — Digital Identity Guidelines: Authentication",
         short_th="NIST SP 800-63B", authority="NIST",
         scope_th="ระดับ AAL, การเก็บรหัสผ่าน, MFA ที่ยอมรับได้",
         controls={"C-IAM-MFA": "AAL2-AAL3", "C-APP-AUTHN": "5.1 Authenticator Requirements"}),

    dict(id="NIST-CSF-2", family="nist", verify=False,
         name_th="NIST Cybersecurity Framework 2.0",
         short_th="NIST CSF 2.0", authority="NIST",
         scope_th="6 หน้าที่: Govern, Identify, Protect, Detect, Respond, Recover",
         controls={"C-OPS-HARDEN": "PR.PS", "C-LOG-SIEM": "DE.AE", "C-OPS-MONITOR": "DE.CM",
                   "C-LOG-NOTIFY": "RS.CO", "C-OPS-BCP": "RC.RP"}),

    dict(id="NIST-800-53r5", family="nist", verify=False,
         name_th="NIST SP 800-53 Rev.5 — Security and Privacy Controls",
         short_th="NIST SP 800-53r5", authority="NIST",
         scope_th="ชุดควบคุมละเอียดตามตระกูล AC, AU, CM, CP, SI ใช้เทียบเคียงมาตรฐานขั้นต่ำของไทย",
         controls={"C-LOG-AUDIT": "AU-2, AU-12", "C-IAM-LEAST": "AC-6",
                   "C-OPS-HARDEN": "CM-6", "C-APP-PENTEST": "CA-8",
                   "C-OPS-BACKUP": "CP-9", "C-SDLC-SAST": "SA-11"}),

    dict(id="NIST-PQC-CSWP39", family="nist", verify=True,
         name_th="NIST Post-Quantum Cryptography Migration (CSWP 39 / PQC Standards)",
         short_th="NIST PQC Migration", authority="NIST / NCCoE",
         scope_th="การทำบัญชีการเข้ารหัสและแผนย้ายไปอัลกอริทึมทนควอนตัม",
         controls={"C-CRY-PQC": "Crypto Discovery & Inventory", "C-CRY-TLS": "Protocol Migration"}),

    # ======================= CIS =======================
    dict(id="CIS-CONTROLS-8", family="cis", verify=False,
         name_th="CIS Critical Security Controls v8.1",
         short_th="CIS Controls v8.1", authority="Center for Internet Security",
         scope_th="18 มาตรการเรียงตามลำดับความสำคัญ เหมาะใช้เป็น roadmap",
         controls={"C-OPS-HARDEN": "Control 4 Secure Configuration",
                   "C-IAM-MFA": "Control 6 Access Control Management",
                   "C-SC-SCA": "Control 7 Continuous Vulnerability Management",
                   "C-SC-REGISTRY": "Control 16 Application Software Security",
                   "C-SC-PKG": "Control 16 Application Software Security",
                   "C-LOG-CENTRAL": "Control 8 Audit Log Management",
                   "C-OPS-DEPLOY": "Control 4.7 Change control",
                   "C-OPS-BACKUP": "Control 11 Data Recovery",
                   "C-APP-PENTEST": "Control 18 Penetration Testing",
                   "C-SDLC-SAST": "Control 16 Application Software Security"}),

    dict(id="CIS-BENCH-K8S", family="cis", verify=False,
         name_th="CIS Benchmarks (Kubernetes / Docker / Linux)",
         short_th="CIS Benchmarks", authority="Center for Internet Security",
         scope_th="เกณฑ์การตั้งค่าระดับระบบปฏิบัติการและ Container Platform",
         controls={"C-OPS-HARDEN": "Benchmark items", "C-OPS-IAC": "Policy enforcement",
                   "C-IAM-LEAST": "RBAC", "C-OPS-RUNTIME": "Runtime policies",
                   "C-SC-IMG": "Image build hardening",
                   "C-SC-CONTAINER": "Image scanning before deploy"}),

    # ======================= Supply chain / SBOM =======================
    dict(id="SLSA-1-0", family="supplychain", verify=False,
         name_th="SLSA v1.0 — Supply-chain Levels for Software Artifacts",
         short_th="SLSA v1.0", authority="OpenSSF",
         scope_th="ระดับ Build L1-L3 พร้อมข้อกำหนดเรื่อง Provenance และ Hermetic Build",
         controls={"C-SC-SIGN": "Build L2-L3 Signed provenance",
                   "C-SDLC-TRACE": "Provenance Available",
                   "C-SC-PIN": "Dependencies Complete",
                   "C-SC-IMG": "Build L3 Hermetic / Isolated build",
                   "C-SC-SBOM": "Provenance content",
                   "C-SC-REGISTRY": "Build L1+ stored in trusted registry",
                   "C-SC-PKG": "Dependencies from verified repository",
                   "C-SC-PROMOTE": "Build L2 provenance stored with release"}),

    dict(id="SPDX-ISO5962", family="supplychain", verify=False,
         name_th="SPDX (ISO/IEC 5962:2021) — รูปแบบมาตรฐานของ SBOM",
         short_th="SPDX / ISO 5962", authority="Linux Foundation / ISO",
         scope_th="รูปแบบไฟล์ SBOM ที่หน่วยงานผู้ว่าจ้างมักระบุให้ส่งมอบ",
         controls={"C-SC-SBOM": "SPDX document", "C-SC-LICENSE": "License expression"}),

    dict(id="CYCLONEDX-ECMA424", family="supplychain", verify=False,
         name_th="CycloneDX (ECMA-424) — รูปแบบมาตรฐานของ SBOM/VEX",
         short_th="CycloneDX / ECMA-424", authority="OWASP / Ecma International",
         scope_th="รองรับ SBOM, VEX และ CBOM (Crypto BOM) ในไฟล์เดียว",
         controls={"C-SC-SBOM": "BOM", "C-SC-SCA": "VEX", "C-CRY-PQC": "CBOM"}),

    # ======================= อุตสาหกรรม / การตรวจรับรอง =======================
    dict(id="PCI-DSS-4", family="industry", verify=False,
         name_th="PCI DSS v4.0 — มาตรฐานความปลอดภัยข้อมูลบัตรชำระเงิน",
         short_th="PCI DSS v4.0", authority="PCI Security Standards Council",
         scope_th="ใช้เมื่อระบบเกี่ยวข้องกับข้อมูลบัตรเครดิต/เดบิต",
         controls={"C-CRY-TLS": "Req 4 Protect data in transit",
                   "C-SDLC-SAST": "Req 6.2 Secure development",
                   "C-SC-SCA": "Req 6.3 Vulnerability management",
                   "C-SC-CONTAINER": "Req 6.3 Vulnerability management",
                   "C-SC-REGISTRY": "Req 6.3 Trusted source of components",
                   "C-SC-PKG": "Req 6.3 Inventory of custom and third-party software",
                   "C-APP-WAF": "Req 6.4.2 Automated technical solution",
                   "C-LOG-CENTRAL": "Req 10 Log and monitor",
                   "C-APP-PENTEST": "Req 11.4 Penetration testing"}),

    dict(id="SOC2-TSC", family="industry", verify=False,
         name_th="SOC 2 — Trust Services Criteria (AICPA)",
         short_th="SOC 2 (TSC)", authority="AICPA",
         scope_th="ใช้เมื่อผู้ว่าจ้างขอรายงานการตรวจสอบจากผู้สอบบัญชีภายนอก",
         controls={"C-LOG-AUDIT": "CC7 System Operations", "C-IAM-LEAST": "CC6 Logical Access",
                   "C-SDLC-REVIEW": "CC8 Change Management", "C-OPS-BCP": "A1.2 Availability",
                   "C-LOG-SIEM": "CC7.2 Monitoring",
                   "C-OPS-DEPLOY": "CC8.1 Change deployment & rollback",
                   "C-SC-PROMOTE": "CC8 Change Management — promoted releases only",
                   "C-SC-REGISTRY": "CC8 Trusted deployment artifacts"}),

    dict(id="CSA-CCM-4", family="industry", verify=False,
         name_th="CSA Cloud Controls Matrix v4 / CSA STAR",
         short_th="CSA CCM v4 / STAR", authority="Cloud Security Alliance",
         scope_th="ชุดควบคุมสำหรับคลาวด์ ใช้ประเมินผู้ให้บริการตามมาตรฐานคลาวด์ของไทย",
         controls={"C-OPS-CSPM": "IVS / DCS", "C-IAM-LEAST": "IAM", "C-CRY-KEY": "CEK",
                   "C-LOG-CENTRAL": "LOG", "C-SC-SBOM": "AIS-06",
                   "C-SC-REGISTRY": "IVS / TVM trusted images",
                   "C-SC-PKG": "STA Supply chain / third-party components"}),

    # ======================= W3C =======================
    dict(id="WCAG-2-2", family="w3c", verify=False,
         name_th="WCAG 2.2 — Web Content Accessibility Guidelines ระดับ AA",
         short_th="WCAG 2.2 AA", authority="W3C",
         scope_th="เกณฑ์การเข้าถึงที่เท่าเทียม ถูกอ้างโดยมาตรฐานเว็บไซต์ภาครัฐไทย",
         controls={"C-WEB-A11Y": "Level AA success criteria"}),
]

# ---------------------------------------------------------------------------
# ชุดมาตรฐานสำเร็จ (Quick Preset) ต่อประเภทโครงการ — ใช้เป็นค่าเริ่มต้นของ checkbox
# ---------------------------------------------------------------------------
FRAMEWORK_PRESETS = {
    "gov": ["TH-CCA-2560", "TH-CYBER-2562", "TH-PDPA-2562", "TH-EGOV-2565",
            "TH-NCSA-MIN-2566", "TH-NCSA-WEB-2568", "TH-DGA-MSPR11-2566",
            "ISO-27001-2022", "OWASP-TOP10-2025", "NIST-SSDF-800-218", "WCAG-2-2"],
    "enterprise": ["TH-PDPA-2562", "TH-CCA-2560", "ISO-27001-2022", "ISO-27701-2019",
                   "OWASP-TOP10-2025", "OWASP-API-2023", "NIST-SSDF-800-218",
                   "CIS-CONTROLS-8", "SOC2-TSC"],
    "internal": ["TH-CCA-2560", "OWASP-TOP10-2025", "NIST-SSDF-800-218", "CIS-CONTROLS-8"],
    "startup": ["OWASP-TOP10-2025", "TH-PDPA-2562"],
    "aiml": ["TH-PDPA-2562", "ISO-27001-2022", "ISO-42001-2023", "OWASP-TOP10-2025",
             "NIST-SSDF-800-218", "SLSA-1-0", "CYCLONEDX-ECMA424"],
    "cloud": ["TH-NCSA-CLOUD-2567", "TH-ETDA-CLOUD", "ISO-27017-2015", "ISO-27018-2019",
              "CSA-CCM-4", "CIS-BENCH-K8S"],
    "payment": ["PCI-DSS-4", "TH-PDPA-2562", "ISO-27001-2022", "OWASP-TOP10-2025",
                "OWASP-ASVS-5", "NIST-800-63B"],
    "supplychain": ["SLSA-1-0", "SPDX-ISO5962", "CYCLONEDX-ECMA424",
                    "NIST-800-161r1", "NIST-SSDF-800-218"],
}

PRESET_LABELS = {
    "gov": "ภาครัฐ / CII (กฎหมายไทยครบชุด)",
    "enterprise": "เอกชน / Enterprise",
    "internal": "Internal Dev / R&D",
    "startup": "Startup (ขั้นต่ำ)",
    "aiml": "โครงการ AI/ML",
    "cloud": "ระบบบนคลาวด์",
    "payment": "ระบบที่เกี่ยวข้องกับการชำระเงิน",
    "supplychain": "เน้น Software Supply Chain",
}
